name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - pytorch=1.7.*
  - tensorflow=2.4.*
  - ipykernel
  - matplotlib
  - jupyter
  - scikit-learn
  - seaborn
  - pillow
  - opencv
  - pyyaml
  - h5py
  - bokeh
  - networkx
  - scipy
  - matplotlib
  - pandas
  - jupyterlab
  - pytest
  - flake8
  - black
  - autopep8
  - isort
